[profile.default]
src = "src"
out = "out"
libs = ["lib"]
via-ir = true
optimizer = true
optimizer_runs = 1000
dotenv = ".env.p256"

fs_permissions = [
  { access = "read", path = "./test/data" }
]

# Add CI profile with same settings
[profile.ci]
src = "src"
out = "out"
libs = ["lib"]
via-ir = true
optimizer = true
optimizer_runs = 1000

fs_permissions = [
  { access = "read", path = "./test/data" }
]

[fmt]
line_length = 100
bracket_spacing = false