[profile.default]
src = "src"
out = "out"
libs = ["lib"]
via-ir = true
optimizer = true
optimizer_runs = 5
dotenv = ".env.p256"

fs_permissions = [
  { access = "read", path = "./test/data" }
]

[profile.default.fuzz]
runs = 256                               
seed = '0x3e8'

[invariant]
runs = 256
depth = 100
fail_on_revert = false
include_storage = true

# Add CI profile with same settings
[profile.ci]
src = "src"
out = "out"
libs = ["lib"]
via-ir = true
optimizer = true
optimizer_runs = 5

fs_permissions = [
  { access = "read", path = "./test/data" }
]

[fmt]
line_length = 100
bracket_spacing = false
