[profile.default]
src = "src"
out = "out"
libs = ["lib"]
via-ir = true
optimizer = true
optimizer_runs = 580
dotenv = ".env.p256"

fs_permissions = [
  { access = "read", path = "./test/data" }
]

# Add CI profile with same settings
[profile.ci]
src = "src"
out = "out"
libs = ["lib"]
via-ir = true
optimizer = true
optimizer_runs = 580

fs_permissions = [
  { access = "read", path = "./test/data" }
]

[fmt]
line_length = 100
bracket_spacing = false

[profile.cov]
ir_minimum = true      # enables viaIR with minimal opts
optimizer = true       # allow minimal optimization under ir_minimum
optimizer_runs = 200
via_ir = true