[profile.default]
src = "src"
out = "out"
libs = ["lib"]
via-ir = true
optimizer = true
optimizer_runs = 645
dotenv = ".env.p256"

fs_permissions = [
  { access = "read", path = "./test/data" }
]

# Add CI profile with same settings
[profile.ci]
src = "src"
out = "out"
libs = ["lib"]
via-ir = true
optimizer = true
optimizer_runs = 645

fs_permissions = [
  { access = "read", path = "./test/data" }
]

[fmt]
  bracket_spacing = true
  int_types = "long"
  line_length = 120
  multiline_func_header = "all"
  number_underscore = "thousands"
  quote_style = "double"
  tab_width = 4
  wrap_comments = true