export const abi = [
    {
       "inputs":[
          {
             "internalType":"address",
             "name":"_entryPoint",
             "type":"address"
          },
          {
             "internalType":"address",
             "name":"_webAuthnVerifier",
             "type":"address"
          },
          {
             "internalType":"uint256",
             "name":"_recoveryPeriod",
             "type":"uint256"
          },
          {
             "internalType":"uint256",
             "name":"_lockPeriod",
             "type":"uint256"
          },
          {
             "internalType":"uint256",
             "name":"_securityPeriod",
             "type":"uint256"
          },
          {
             "internalType":"uint256",
             "name":"_securityWindow",
             "type":"uint256"
          }
       ],
       "stateMutability":"nonpayable",
       "type":"constructor"
    },
    {
       "inputs":[
          
       ],
       "name":"ECDSAInvalidSignature",
       "type":"error"
    },
    {
       "inputs":[
          {
             "internalType":"uint256",
             "name":"length",
             "type":"uint256"
          }
       ],
       "name":"ECDSAInvalidSignatureLength",
       "type":"error"
    },
    {
       "inputs":[
          {
             "internalType":"bytes32",
             "name":"s",
             "type":"bytes32"
          }
       ],
       "name":"ECDSAInvalidSignatureS",
       "type":"error"
    },
    {
       "inputs":[
          {
             "internalType":"uint256",
             "name":"index",
             "type":"uint256"
          },
          {
             "internalType":"bytes",
             "name":"error",
             "type":"bytes"
          }
       ],
       "name":"ExecuteError",
       "type":"error"
    },
    {
       "inputs":[
          
       ],
       "name":"InvalidInitialization",
       "type":"error"
    },
    {
       "inputs":[
          
       ],
       "name":"InvalidShortString",
       "type":"error"
    },
    {
       "inputs":[
          
       ],
       "name":"KeyManager__AddressCantBeZero",
       "type":"error"
    },
    {
       "inputs":[
          
       ],
       "name":"KeyManager__InvalidTimestamp",
       "type":"error"
    },
    {
       "inputs":[
          
       ],
       "name":"KeyManager__KeyInactive",
       "type":"error"
    },
    {
       "inputs":[
          
       ],
       "name":"KeyManager__KeyRegistered",
       "type":"error"
    },
    {
       "inputs":[
          
       ],
       "name":"KeyManager__MustIncludeLimits",
       "type":"error"
    },
    {
       "inputs":[
          
       ],
       "name":"KeyManager__SelectorsListTooBig",
       "type":"error"
    },
    {
       "inputs":[
          
       ],
       "name":"NotFromEntryPoint",
       "type":"error"
    },
    {
       "inputs":[
          
       ],
       "name":"NotInitializing",
       "type":"error"
    },
    {
       "inputs":[
          
       ],
       "name":"OPF7702Recoverable__AccountLocked",
       "type":"error"
    },
    {
       "inputs":[
          
       ],
       "name":"OPF7702Recoverable__AddressCantBeZero",
       "type":"error"
    },
    {
       "inputs":[
          
       ],
       "name":"OPF7702Recoverable__DuplicatedGuardian",
       "type":"error"
    },
    {
       "inputs":[
          
       ],
       "name":"OPF7702Recoverable__DuplicatedProposal",
       "type":"error"
    },
    {
       "inputs":[
          
       ],
       "name":"OPF7702Recoverable__DuplicatedRevoke",
       "type":"error"
    },
    {
       "inputs":[
          
       ],
       "name":"OPF7702Recoverable__GuardianCannotBeAddressThis",
       "type":"error"
    },
    {
       "inputs":[
          
       ],
       "name":"OPF7702Recoverable__GuardianCannotBeCurrentMasterKey",
       "type":"error"
    },
    {
       "inputs":[
          
       ],
       "name":"OPF7702Recoverable__GuardianCannotBeOwner",
       "type":"error"
    },
    {
       "inputs":[
          
       ],
       "name":"OPF7702Recoverable__InvalidRecoverySignatures",
       "type":"error"
    },
    {
       "inputs":[
          
       ],
       "name":"OPF7702Recoverable__InvalidSignatureAmount",
       "type":"error"
    },
    {
       "inputs":[
          
       ],
       "name":"OPF7702Recoverable__MustBeGuardian",
       "type":"error"
    },
    {
       "inputs":[
          
       ],
       "name":"OPF7702Recoverable__NoGuardiansSetOnWallet",
       "type":"error"
    },
    {
       "inputs":[
          
       ],
       "name":"OPF7702Recoverable__NoOngoingRecovery",
       "type":"error"
    },
    {
       "inputs":[
          
       ],
       "name":"OPF7702Recoverable__OngoingRecovery",
       "type":"error"
    },
    {
       "inputs":[
          
       ],
       "name":"OPF7702Recoverable__PendingProposalExpired",
       "type":"error"
    },
    {
       "inputs":[
          
       ],
       "name":"OPF7702Recoverable__PendingProposalNotOver",
       "type":"error"
    },
    {
       "inputs":[
          
       ],
       "name":"OPF7702Recoverable__PendingRevokeExpired",
       "type":"error"
    },
    {
       "inputs":[
          
       ],
       "name":"OPF7702Recoverable__PendingRevokeNotOver",
       "type":"error"
    },
    {
       "inputs":[
          
       ],
       "name":"OPF7702Recoverable__RecoverCannotBeActiveKey",
       "type":"error"
    },
    {
       "inputs":[
          
       ],
       "name":"OPF7702Recoverable__UnknownProposal",
       "type":"error"
    },
    {
       "inputs":[
          
       ],
       "name":"OPF7702Recoverable__UnknownRevoke",
       "type":"error"
    },
    {
       "inputs":[
          
       ],
       "name":"OPF7702Recoverable__UnsupportedKeyType",
       "type":"error"
    },
    {
       "inputs":[
          
       ],
       "name":"OpenfortBaseAccount7702V1_UnauthorizedCaller",
       "type":"error"
    },
    {
       "inputs":[
          
       ],
       "name":"OpenfortBaseAccount7702V1__InvalidSignature",
       "type":"error"
    },
    {
       "inputs":[
          
       ],
       "name":"OpenfortBaseAccount7702V1__InvalidTransactionLength",
       "type":"error"
    },
    {
       "inputs":[
          {
             "internalType":"uint256",
             "name":"total",
             "type":"uint256"
          },
          {
             "internalType":"uint256",
             "name":"max",
             "type":"uint256"
          }
       ],
       "name":"OpenfortBaseAccount7702V1__TooManyCalls",
       "type":"error"
    },
    {
       "inputs":[
          
       ],
       "name":"OpenfortBaseAccount7702V1__UnsupportedExecutionMode",
       "type":"error"
    },
    {
       "inputs":[
          
       ],
       "name":"OpenfortBaseAccount7702V1__UnsupportedOpData",
       "type":"error"
    },
    {
       "inputs":[
          
       ],
       "name":"ReentrancyGuardReentrantCall",
       "type":"error"
    },
    {
       "inputs":[
          {
             "internalType":"uint8",
             "name":"bits",
             "type":"uint8"
          },
          {
             "internalType":"uint256",
             "name":"value",
             "type":"uint256"
          }
       ],
       "name":"SafeCastOverflowedUintDowncast",
       "type":"error"
    },
    {
       "inputs":[
          {
             "internalType":"string",
             "name":"str",
             "type":"string"
          }
       ],
       "name":"StringTooLong",
       "type":"error"
    },
    {
       "inputs":[
          
       ],
       "name":"UpgradeAddress__AddressCantBeZero",
       "type":"error"
    },
    {
       "inputs":[
          
       ],
       "name":"UpgradeAddress__AddressNotCanonical",
       "type":"error"
    },
    {
       "anonymous":false,
       "inputs":[
          {
             "indexed":true,
             "internalType":"address",
             "name":"source",
             "type":"address"
          },
          {
             "indexed":false,
             "internalType":"uint256",
             "name":"amount",
             "type":"uint256"
          }
       ],
       "name":"DepositAdded",
       "type":"event"
    },
    {
       "anonymous":false,
       "inputs":[
          
       ],
       "name":"EIP712DomainChanged",
       "type":"event"
    },
    {
       "anonymous":false,
       "inputs":[
          {
             "indexed":true,
             "internalType":"address",
             "name":"previous",
             "type":"address"
          },
          {
             "indexed":true,
             "internalType":"address",
             "name":"current",
             "type":"address"
          }
       ],
       "name":"EntryPointUpdated",
       "type":"event"
    },
    {
       "anonymous":false,
       "inputs":[
          {
             "indexed":true,
             "internalType":"bytes32",
             "name":"guardianHash",
             "type":"bytes32"
          }
       ],
       "name":"GuardianAdded",
       "type":"event"
    },
    {
       "anonymous":false,
       "inputs":[
          {
             "indexed":true,
             "internalType":"bytes32",
             "name":"guardianHash",
             "type":"bytes32"
          }
       ],
       "name":"GuardianProposalCancelled",
       "type":"event"
    },
    {
       "anonymous":false,
       "inputs":[
          {
             "indexed":true,
             "internalType":"bytes32",
             "name":"guardianHash",
             "type":"bytes32"
          },
          {
             "indexed":false,
             "internalType":"uint256",
             "name":"executeAfter",
             "type":"uint256"
          }
       ],
       "name":"GuardianProposed",
       "type":"event"
    },
    {
       "anonymous":false,
       "inputs":[
          {
             "indexed":true,
             "internalType":"bytes32",
             "name":"guardianHash",
             "type":"bytes32"
          }
       ],
       "name":"GuardianRemoved",
       "type":"event"
    },
    {
       "anonymous":false,
       "inputs":[
          {
             "indexed":true,
             "internalType":"bytes32",
             "name":"guardianHash",
             "type":"bytes32"
          }
       ],
       "name":"GuardianRevocationCancelled",
       "type":"event"
    },
    {
       "anonymous":false,
       "inputs":[
          {
             "indexed":true,
             "internalType":"bytes32",
             "name":"guardianHash",
             "type":"bytes32"
          },
          {
             "indexed":false,
             "internalType":"uint256",
             "name":"executeAfter",
             "type":"uint256"
          }
       ],
       "name":"GuardianRevocationScheduled",
       "type":"event"
    },
    {
       "anonymous":false,
       "inputs":[
          {
             "indexed":false,
             "internalType":"uint64",
             "name":"version",
             "type":"uint64"
          }
       ],
       "name":"Initialized",
       "type":"event"
    },
    {
       "anonymous":false,
       "inputs":[
          {
             "components":[
                {
                   "components":[
                      {
                         "internalType":"bytes32",
                         "name":"x",
                         "type":"bytes32"
                      },
                      {
                         "internalType":"bytes32",
                         "name":"y",
                         "type":"bytes32"
                      }
                   ],
                   "internalType":"struct IKey.PubKey",
                   "name":"pubKey",
                   "type":"tuple"
                },
                {
                   "internalType":"address",
                   "name":"eoaAddress",
                   "type":"address"
                },
                {
                   "internalType":"enum IKey.KeyType",
                   "name":"keyType",
                   "type":"uint8"
                }
             ],
             "indexed":true,
             "internalType":"struct IKey.Key",
             "name":"masterKey",
             "type":"tuple"
          }
       ],
       "name":"Initialized",
       "type":"event"
    },
    {
       "anonymous":false,
       "inputs":[
          {
             "indexed":true,
             "internalType":"bytes32",
             "name":"key",
             "type":"bytes32"
          }
       ],
       "name":"KeyRegistrated",
       "type":"event"
    },
    {
       "anonymous":false,
       "inputs":[
          {
             "indexed":true,
             "internalType":"bytes32",
             "name":"key",
             "type":"bytes32"
          }
       ],
       "name":"KeyRevoked",
       "type":"event"
    },
    {
       "anonymous":false,
       "inputs":[
          
       ],
       "name":"RecoveryCancelled",
       "type":"event"
    },
    {
       "anonymous":false,
       "inputs":[
          
       ],
       "name":"RecoveryCompleted",
       "type":"event"
    },
    {
       "anonymous":false,
       "inputs":[
          {
             "indexed":false,
             "internalType":"uint64",
             "name":"executeAfter",
             "type":"uint64"
          },
          {
             "indexed":false,
             "internalType":"uint32",
             "name":"guardiansRequired",
             "type":"uint32"
          }
       ],
       "name":"RecoveryStarted",
       "type":"event"
    },
    {
       "anonymous":false,
       "inputs":[
          {
             "indexed":false,
             "internalType":"bool",
             "name":"isLocked",
             "type":"bool"
          }
       ],
       "name":"WalletLocked",
       "type":"event"
    },
    {
       "anonymous":false,
       "inputs":[
          {
             "indexed":true,
             "internalType":"address",
             "name":"previous",
             "type":"address"
          },
          {
             "indexed":true,
             "internalType":"address",
             "name":"current",
             "type":"address"
          }
       ],
       "name":"WebAuthnVerifierUpdated",
       "type":"event"
    },
    {
       "stateMutability":"payable",
       "type":"fallback"
    },
    {
       "inputs":[
          
       ],
       "name":"CUSTOM_STORAGE_ROOT",
       "outputs":[
          {
             "internalType":"bytes32",
             "name":"",
             "type":"bytes32"
          }
       ],
       "stateMutability":"view",
       "type":"function"
    },
    {
       "inputs":[
          
       ],
       "name":"WEBAUTHN_VERIFIER",
       "outputs":[
          {
             "internalType":"address",
             "name":"",
             "type":"address"
          }
       ],
       "stateMutability":"view",
       "type":"function"
    },
    {
       "inputs":[
          
       ],
       "name":"_OPENFORT_CONTRACT_ADDRESS",
       "outputs":[
          {
             "internalType":"address",
             "name":"",
             "type":"address"
          }
       ],
       "stateMutability":"view",
       "type":"function"
    },
    {
       "inputs":[
          {
             "internalType":"bytes32",
             "name":"_guardian",
             "type":"bytes32"
          }
       ],
       "name":"cancelGuardianProposal",
       "outputs":[
          
       ],
       "stateMutability":"nonpayable",
       "type":"function"
    },
    {
       "inputs":[
          {
             "internalType":"bytes32",
             "name":"_guardian",
             "type":"bytes32"
          }
       ],
       "name":"cancelGuardianRevocation",
       "outputs":[
          
       ],
       "stateMutability":"nonpayable",
       "type":"function"
    },
    {
       "inputs":[
          
       ],
       "name":"cancelRecovery",
       "outputs":[
          
       ],
       "stateMutability":"nonpayable",
       "type":"function"
    },
    {
       "inputs":[
          {
             "internalType":"bytes[]",
             "name":"_signatures",
             "type":"bytes[]"
          }
       ],
       "name":"completeRecovery",
       "outputs":[
          
       ],
       "stateMutability":"nonpayable",
       "type":"function"
    },
    {
       "inputs":[
          {
             "internalType":"bytes32",
             "name":"_guardian",
             "type":"bytes32"
          }
       ],
       "name":"confirmGuardianProposal",
       "outputs":[
          
       ],
       "stateMutability":"nonpayable",
       "type":"function"
    },
    {
       "inputs":[
          {
             "internalType":"bytes32",
             "name":"_guardian",
             "type":"bytes32"
          }
       ],
       "name":"confirmGuardianRevocation",
       "outputs":[
          
       ],
       "stateMutability":"nonpayable",
       "type":"function"
    },
    {
       "inputs":[
          
       ],
       "name":"eip712Domain",
       "outputs":[
          {
             "internalType":"bytes1",
             "name":"fields",
             "type":"bytes1"
          },
          {
             "internalType":"string",
             "name":"name",
             "type":"string"
          },
          {
             "internalType":"string",
             "name":"version",
             "type":"string"
          },
          {
             "internalType":"uint256",
             "name":"chainId",
             "type":"uint256"
          },
          {
             "internalType":"address",
             "name":"verifyingContract",
             "type":"address"
          },
          {
             "internalType":"bytes32",
             "name":"salt",
             "type":"bytes32"
          },
          {
             "internalType":"uint256[]",
             "name":"extensions",
             "type":"uint256[]"
          }
       ],
       "stateMutability":"view",
       "type":"function"
    },
    {
       "inputs":[
          {
             "internalType":"bytes",
             "name":"_signature",
             "type":"bytes"
          }
       ],
       "name":"encodeEOASignature",
       "outputs":[
          {
             "internalType":"bytes",
             "name":"",
             "type":"bytes"
          }
       ],
       "stateMutability":"pure",
       "type":"function"
    },
    {
       "inputs":[
          {
             "internalType":"bytes32",
             "name":"r",
             "type":"bytes32"
          },
          {
             "internalType":"bytes32",
             "name":"s",
             "type":"bytes32"
          },
          {
             "components":[
                {
                   "internalType":"bytes32",
                   "name":"x",
                   "type":"bytes32"
                },
                {
                   "internalType":"bytes32",
                   "name":"y",
                   "type":"bytes32"
                }
             ],
             "internalType":"struct IKey.PubKey",
             "name":"pubKey",
             "type":"tuple"
          },
          {
             "internalType":"enum IKey.KeyType",
             "name":"_keyType",
             "type":"uint8"
          }
       ],
       "name":"encodeP256Signature",
       "outputs":[
          {
             "internalType":"bytes",
             "name":"",
             "type":"bytes"
          }
       ],
       "stateMutability":"pure",
       "type":"function"
    },
    {
       "inputs":[
          {
             "internalType":"bool",
             "name":"requireUserVerification",
             "type":"bool"
          },
          {
             "internalType":"bytes",
             "name":"authenticatorData",
             "type":"bytes"
          },
          {
             "internalType":"string",
             "name":"clientDataJSON",
             "type":"string"
          },
          {
             "internalType":"uint256",
             "name":"challengeIndex",
             "type":"uint256"
          },
          {
             "internalType":"uint256",
             "name":"typeIndex",
             "type":"uint256"
          },
          {
             "internalType":"bytes32",
             "name":"r",
             "type":"bytes32"
          },
          {
             "internalType":"bytes32",
             "name":"s",
             "type":"bytes32"
          },
          {
             "components":[
                {
                   "internalType":"bytes32",
                   "name":"x",
                   "type":"bytes32"
                },
                {
                   "internalType":"bytes32",
                   "name":"y",
                   "type":"bytes32"
                }
             ],
             "internalType":"struct IKey.PubKey",
             "name":"pubKey",
             "type":"tuple"
          }
       ],
       "name":"encodeWebAuthnSignature",
       "outputs":[
          {
             "internalType":"bytes",
             "name":"",
             "type":"bytes"
          }
       ],
       "stateMutability":"pure",
       "type":"function"
    },
    {
       "inputs":[
          
       ],
       "name":"entryPoint",
       "outputs":[
          {
             "internalType":"contract IEntryPoint",
             "name":"",
             "type":"address"
          }
       ],
       "stateMutability":"view",
       "type":"function"
    },
    {
       "inputs":[
          {
             "internalType":"address",
             "name":"target",
             "type":"address"
          },
          {
             "internalType":"uint256",
             "name":"value",
             "type":"uint256"
          },
          {
             "internalType":"bytes",
             "name":"data",
             "type":"bytes"
          }
       ],
       "name":"execute",
       "outputs":[
          
       ],
       "stateMutability":"nonpayable",
       "type":"function"
    },
    {
       "inputs":[
          {
             "internalType":"bytes32",
             "name":"mode",
             "type":"bytes32"
          },
          {
             "internalType":"bytes",
             "name":"executionData",
             "type":"bytes"
          }
       ],
       "name":"execute",
       "outputs":[
          
       ],
       "stateMutability":"payable",
       "type":"function"
    },
    {
       "inputs":[
          {
             "components":[
                {
                   "internalType":"address",
                   "name":"target",
                   "type":"address"
                },
                {
                   "internalType":"uint256",
                   "name":"value",
                   "type":"uint256"
                },
                {
                   "internalType":"bytes",
                   "name":"data",
                   "type":"bytes"
                }
             ],
             "internalType":"struct BaseAccount.Call[]",
             "name":"calls",
             "type":"tuple[]"
          }
       ],
       "name":"executeBatch",
       "outputs":[
          
       ],
       "stateMutability":"nonpayable",
       "type":"function"
    },
    {
       "inputs":[
          {
             "components":[
                {
                   "components":[
                      {
                         "internalType":"bytes32",
                         "name":"x",
                         "type":"bytes32"
                      },
                      {
                         "internalType":"bytes32",
                         "name":"y",
                         "type":"bytes32"
                      }
                   ],
                   "internalType":"struct IKey.PubKey",
                   "name":"pubKey",
                   "type":"tuple"
                },
                {
                   "internalType":"address",
                   "name":"eoaAddress",
                   "type":"address"
                },
                {
                   "internalType":"enum IKey.KeyType",
                   "name":"keyType",
                   "type":"uint8"
                }
             ],
             "internalType":"struct IKey.Key",
             "name":"_key",
             "type":"tuple"
          },
          {
             "internalType":"bytes32",
             "name":"_initialGuardian",
             "type":"bytes32"
          }
       ],
       "name":"getDigestToInit",
       "outputs":[
          {
             "internalType":"bytes32",
             "name":"digest",
             "type":"bytes32"
          }
       ],
       "stateMutability":"view",
       "type":"function"
    },
    {
       "inputs":[
          
       ],
       "name":"getDigestToSign",
       "outputs":[
          {
             "internalType":"bytes32",
             "name":"digest",
             "type":"bytes32"
          }
       ],
       "stateMutability":"view",
       "type":"function"
    },
    {
       "inputs":[
          
       ],
       "name":"getGuardians",
       "outputs":[
          {
             "internalType":"bytes32[]",
             "name":"",
             "type":"bytes32[]"
          }
       ],
       "stateMutability":"view",
       "type":"function"
    },
    {
       "inputs":[
          {
             "internalType":"uint256",
             "name":"_id",
             "type":"uint256"
          }
       ],
       "name":"getKeyById",
       "outputs":[
          {
             "components":[
                {
                   "components":[
                      {
                         "internalType":"bytes32",
                         "name":"x",
                         "type":"bytes32"
                      },
                      {
                         "internalType":"bytes32",
                         "name":"y",
                         "type":"bytes32"
                      }
                   ],
                   "internalType":"struct IKey.PubKey",
                   "name":"pubKey",
                   "type":"tuple"
                },
                {
                   "internalType":"address",
                   "name":"eoaAddress",
                   "type":"address"
                },
                {
                   "internalType":"enum IKey.KeyType",
                   "name":"keyType",
                   "type":"uint8"
                }
             ],
             "internalType":"struct IKey.Key",
             "name":"",
             "type":"tuple"
          }
       ],
       "stateMutability":"view",
       "type":"function"
    },
    {
       "inputs":[
          {
             "internalType":"bytes32",
             "name":"_keyHash",
             "type":"bytes32"
          }
       ],
       "name":"getKeyData",
       "outputs":[
          {
             "internalType":"bool",
             "name":"isActive",
             "type":"bool"
          },
          {
             "internalType":"uint48",
             "name":"validUntil",
             "type":"uint48"
          },
          {
             "internalType":"uint48",
             "name":"validAfter",
             "type":"uint48"
          },
          {
             "internalType":"uint48",
             "name":"limit",
             "type":"uint48"
          }
       ],
       "stateMutability":"view",
       "type":"function"
    },
    {
       "inputs":[
          {
             "internalType":"uint256",
             "name":"_id",
             "type":"uint256"
          }
       ],
       "name":"getKeyRegistrationInfo",
       "outputs":[
          {
             "internalType":"enum IKey.KeyType",
             "name":"keyType",
             "type":"uint8"
          },
          {
             "internalType":"address",
             "name":"registeredBy",
             "type":"address"
          },
          {
             "internalType":"bool",
             "name":"isActive",
             "type":"bool"
          }
       ],
       "stateMutability":"view",
       "type":"function"
    },
    {
       "inputs":[
          
       ],
       "name":"getNonce",
       "outputs":[
          {
             "internalType":"uint256",
             "name":"",
             "type":"uint256"
          }
       ],
       "stateMutability":"view",
       "type":"function"
    },
    {
       "inputs":[
          {
             "internalType":"bytes32",
             "name":"_guardian",
             "type":"bytes32"
          }
       ],
       "name":"getPendingStatusGuardians",
       "outputs":[
          {
             "internalType":"uint256",
             "name":"",
             "type":"uint256"
          }
       ],
       "stateMutability":"view",
       "type":"function"
    },
    {
       "inputs":[
          
       ],
       "name":"guardianCount",
       "outputs":[
          {
             "internalType":"uint256",
             "name":"",
             "type":"uint256"
          }
       ],
       "stateMutability":"view",
       "type":"function"
    },
    {
       "inputs":[
          
       ],
       "name":"id",
       "outputs":[
          {
             "internalType":"uint256",
             "name":"",
             "type":"uint256"
          }
       ],
       "stateMutability":"view",
       "type":"function"
    },
    {
       "inputs":[
          {
             "internalType":"uint256",
             "name":"",
             "type":"uint256"
          }
       ],
       "name":"idKeys",
       "outputs":[
          {
             "components":[
                {
                   "internalType":"bytes32",
                   "name":"x",
                   "type":"bytes32"
                },
                {
                   "internalType":"bytes32",
                   "name":"y",
                   "type":"bytes32"
                }
             ],
             "internalType":"struct IKey.PubKey",
             "name":"pubKey",
             "type":"tuple"
          },
          {
             "internalType":"address",
             "name":"eoaAddress",
             "type":"address"
          },
          {
             "internalType":"enum IKey.KeyType",
             "name":"keyType",
             "type":"uint8"
          }
       ],
       "stateMutability":"view",
       "type":"function"
    },
    {
       "inputs":[
          {
             "components":[
                {
                   "components":[
                      {
                         "internalType":"bytes32",
                         "name":"x",
                         "type":"bytes32"
                      },
                      {
                         "internalType":"bytes32",
                         "name":"y",
                         "type":"bytes32"
                      }
                   ],
                   "internalType":"struct IKey.PubKey",
                   "name":"pubKey",
                   "type":"tuple"
                },
                {
                   "internalType":"address",
                   "name":"eoaAddress",
                   "type":"address"
                },
                {
                   "internalType":"enum IKey.KeyType",
                   "name":"keyType",
                   "type":"uint8"
                }
             ],
             "internalType":"struct IKey.Key",
             "name":"_key",
             "type":"tuple"
          },
          {
             "components":[
                {
                   "internalType":"uint48",
                   "name":"validUntil",
                   "type":"uint48"
                },
                {
                   "internalType":"uint48",
                   "name":"validAfter",
                   "type":"uint48"
                },
                {
                   "internalType":"uint48",
                   "name":"limit",
                   "type":"uint48"
                },
                {
                   "internalType":"bool",
                   "name":"whitelisting",
                   "type":"bool"
                },
                {
                   "internalType":"address",
                   "name":"contractAddress",
                   "type":"address"
                },
                {
                   "components":[
                      {
                         "internalType":"address",
                         "name":"token",
                         "type":"address"
                      },
                      {
                         "internalType":"uint256",
                         "name":"limit",
                         "type":"uint256"
                      }
                   ],
                   "internalType":"struct SpendLimit.SpendTokenInfo",
                   "name":"spendTokenInfo",
                   "type":"tuple"
                },
                {
                   "internalType":"bytes4[]",
                   "name":"allowedSelectors",
                   "type":"bytes4[]"
                },
                {
                   "internalType":"uint256",
                   "name":"ethLimit",
                   "type":"uint256"
                }
             ],
             "internalType":"struct IKey.KeyReg",
             "name":"_keyData",
             "type":"tuple"
          },
          {
             "internalType":"bytes",
             "name":"_signature",
             "type":"bytes"
          },
          {
             "internalType":"bytes32",
             "name":"_initialGuardian",
             "type":"bytes32"
          }
       ],
       "name":"initialize",
       "outputs":[
          
       ],
       "stateMutability":"nonpayable",
       "type":"function"
    },
    {
       "inputs":[
          {
             "internalType":"bytes32",
             "name":"_guardian",
             "type":"bytes32"
          }
       ],
       "name":"isGuardian",
       "outputs":[
          {
             "internalType":"bool",
             "name":"",
             "type":"bool"
          }
       ],
       "stateMutability":"view",
       "type":"function"
    },
    {
       "inputs":[
          {
             "internalType":"bytes32",
             "name":"keyHash",
             "type":"bytes32"
          }
       ],
       "name":"isKeyActive",
       "outputs":[
          {
             "internalType":"bool",
             "name":"",
             "type":"bool"
          }
       ],
       "stateMutability":"view",
       "type":"function"
    },
    {
       "inputs":[
          
       ],
       "name":"isLocked",
       "outputs":[
          {
             "internalType":"bool",
             "name":"",
             "type":"bool"
          }
       ],
       "stateMutability":"view",
       "type":"function"
    },
    {
       "inputs":[
          {
             "internalType":"bytes32",
             "name":"_hash",
             "type":"bytes32"
          },
          {
             "internalType":"bytes",
             "name":"_signature",
             "type":"bytes"
          }
       ],
       "name":"isValidSignature",
       "outputs":[
          {
             "internalType":"bytes4",
             "name":"",
             "type":"bytes4"
          }
       ],
       "stateMutability":"view",
       "type":"function"
    },
    {
       "inputs":[
          {
             "internalType":"bytes32",
             "name":"",
             "type":"bytes32"
          }
       ],
       "name":"keys",
       "outputs":[
          {
             "components":[
                {
                   "internalType":"bytes32",
                   "name":"x",
                   "type":"bytes32"
                },
                {
                   "internalType":"bytes32",
                   "name":"y",
                   "type":"bytes32"
                }
             ],
             "internalType":"struct IKey.PubKey",
             "name":"pubKey",
             "type":"tuple"
          },
          {
             "internalType":"bool",
             "name":"isActive",
             "type":"bool"
          },
          {
             "internalType":"uint48",
             "name":"validUntil",
             "type":"uint48"
          },
          {
             "internalType":"uint48",
             "name":"validAfter",
             "type":"uint48"
          },
          {
             "internalType":"uint48",
             "name":"limit",
             "type":"uint48"
          },
          {
             "internalType":"bool",
             "name":"masterKey",
             "type":"bool"
          },
          {
             "internalType":"bool",
             "name":"whitelisting",
             "type":"bool"
          },
          {
             "components":[
                {
                   "internalType":"address",
                   "name":"token",
                   "type":"address"
                },
                {
                   "internalType":"uint256",
                   "name":"limit",
                   "type":"uint256"
                }
             ],
             "internalType":"struct SpendLimit.SpendTokenInfo",
             "name":"spendTokenInfo",
             "type":"tuple"
          },
          {
             "internalType":"uint256",
             "name":"ethLimit",
             "type":"uint256"
          },
          {
             "internalType":"address",
             "name":"whoRegistrated",
             "type":"address"
          }
       ],
       "stateMutability":"view",
       "type":"function"
    },
    {
       "inputs":[
          
       ],
       "name":"namespaceAndVersion",
       "outputs":[
          {
             "internalType":"string",
             "name":"",
             "type":"string"
          }
       ],
       "stateMutability":"pure",
       "type":"function"
    },
    {
       "inputs":[
          {
             "internalType":"address",
             "name":"",
             "type":"address"
          },
          {
             "internalType":"address",
             "name":"",
             "type":"address"
          },
          {
             "internalType":"uint256[]",
             "name":"",
             "type":"uint256[]"
          },
          {
             "internalType":"uint256[]",
             "name":"",
             "type":"uint256[]"
          },
          {
             "internalType":"bytes",
             "name":"",
             "type":"bytes"
          }
       ],
       "name":"onERC1155BatchReceived",
       "outputs":[
          {
             "internalType":"bytes4",
             "name":"",
             "type":"bytes4"
          }
       ],
       "stateMutability":"nonpayable",
       "type":"function"
    },
    {
       "inputs":[
          {
             "internalType":"address",
             "name":"",
             "type":"address"
          },
          {
             "internalType":"address",
             "name":"",
             "type":"address"
          },
          {
             "internalType":"uint256",
             "name":"",
             "type":"uint256"
          },
          {
             "internalType":"uint256",
             "name":"",
             "type":"uint256"
          },
          {
             "internalType":"bytes",
             "name":"",
             "type":"bytes"
          }
       ],
       "name":"onERC1155Received",
       "outputs":[
          {
             "internalType":"bytes4",
             "name":"",
             "type":"bytes4"
          }
       ],
       "stateMutability":"nonpayable",
       "type":"function"
    },
    {
       "inputs":[
          {
             "internalType":"address",
             "name":"",
             "type":"address"
          },
          {
             "internalType":"address",
             "name":"",
             "type":"address"
          },
          {
             "internalType":"uint256",
             "name":"",
             "type":"uint256"
          },
          {
             "internalType":"bytes",
             "name":"",
             "type":"bytes"
          }
       ],
       "name":"onERC721Received",
       "outputs":[
          {
             "internalType":"bytes4",
             "name":"",
             "type":"bytes4"
          }
       ],
       "stateMutability":"nonpayable",
       "type":"function"
    },
    {
       "inputs":[
          {
             "internalType":"bytes32",
             "name":"_guardian",
             "type":"bytes32"
          }
       ],
       "name":"proposeGuardian",
       "outputs":[
          
       ],
       "stateMutability":"nonpayable",
       "type":"function"
    },
    {
       "inputs":[
          
       ],
       "name":"recoveryData",
       "outputs":[
          {
             "components":[
                {
                   "components":[
                      {
                         "internalType":"bytes32",
                         "name":"x",
                         "type":"bytes32"
                      },
                      {
                         "internalType":"bytes32",
                         "name":"y",
                         "type":"bytes32"
                      }
                   ],
                   "internalType":"struct IKey.PubKey",
                   "name":"pubKey",
                   "type":"tuple"
                },
                {
                   "internalType":"address",
                   "name":"eoaAddress",
                   "type":"address"
                },
                {
                   "internalType":"enum IKey.KeyType",
                   "name":"keyType",
                   "type":"uint8"
                }
             ],
             "internalType":"struct IKey.Key",
             "name":"key",
             "type":"tuple"
          },
          {
             "internalType":"uint64",
             "name":"executeAfter",
             "type":"uint64"
          },
          {
             "internalType":"uint32",
             "name":"guardiansRequired",
             "type":"uint32"
          }
       ],
       "stateMutability":"view",
       "type":"function"
    },
    {
       "inputs":[
          {
             "components":[
                {
                   "components":[
                      {
                         "internalType":"bytes32",
                         "name":"x",
                         "type":"bytes32"
                      },
                      {
                         "internalType":"bytes32",
                         "name":"y",
                         "type":"bytes32"
                      }
                   ],
                   "internalType":"struct IKey.PubKey",
                   "name":"pubKey",
                   "type":"tuple"
                },
                {
                   "internalType":"address",
                   "name":"eoaAddress",
                   "type":"address"
                },
                {
                   "internalType":"enum IKey.KeyType",
                   "name":"keyType",
                   "type":"uint8"
                }
             ],
             "internalType":"struct IKey.Key",
             "name":"_key",
             "type":"tuple"
          },
          {
             "components":[
                {
                   "internalType":"uint48",
                   "name":"validUntil",
                   "type":"uint48"
                },
                {
                   "internalType":"uint48",
                   "name":"validAfter",
                   "type":"uint48"
                },
                {
                   "internalType":"uint48",
                   "name":"limit",
                   "type":"uint48"
                },
                {
                   "internalType":"bool",
                   "name":"whitelisting",
                   "type":"bool"
                },
                {
                   "internalType":"address",
                   "name":"contractAddress",
                   "type":"address"
                },
                {
                   "components":[
                      {
                         "internalType":"address",
                         "name":"token",
                         "type":"address"
                      },
                      {
                         "internalType":"uint256",
                         "name":"limit",
                         "type":"uint256"
                      }
                   ],
                   "internalType":"struct SpendLimit.SpendTokenInfo",
                   "name":"spendTokenInfo",
                   "type":"tuple"
                },
                {
                   "internalType":"bytes4[]",
                   "name":"allowedSelectors",
                   "type":"bytes4[]"
                },
                {
                   "internalType":"uint256",
                   "name":"ethLimit",
                   "type":"uint256"
                }
             ],
             "internalType":"struct IKey.KeyReg",
             "name":"_keyData",
             "type":"tuple"
          }
       ],
       "name":"registerKey",
       "outputs":[
          
       ],
       "stateMutability":"nonpayable",
       "type":"function"
    },
    {
       "inputs":[
          
       ],
       "name":"revokeAllKeys",
       "outputs":[
          
       ],
       "stateMutability":"nonpayable",
       "type":"function"
    },
    {
       "inputs":[
          {
             "internalType":"bytes32",
             "name":"_guardian",
             "type":"bytes32"
          }
       ],
       "name":"revokeGuardian",
       "outputs":[
          
       ],
       "stateMutability":"nonpayable",
       "type":"function"
    },
    {
       "inputs":[
          {
             "components":[
                {
                   "components":[
                      {
                         "internalType":"bytes32",
                         "name":"x",
                         "type":"bytes32"
                      },
                      {
                         "internalType":"bytes32",
                         "name":"y",
                         "type":"bytes32"
                      }
                   ],
                   "internalType":"struct IKey.PubKey",
                   "name":"pubKey",
                   "type":"tuple"
                },
                {
                   "internalType":"address",
                   "name":"eoaAddress",
                   "type":"address"
                },
                {
                   "internalType":"enum IKey.KeyType",
                   "name":"keyType",
                   "type":"uint8"
                }
             ],
             "internalType":"struct IKey.Key",
             "name":"_key",
             "type":"tuple"
          }
       ],
       "name":"revokeKey",
       "outputs":[
          
       ],
       "stateMutability":"nonpayable",
       "type":"function"
    },
    {
       "inputs":[
          {
             "internalType":"address",
             "name":"_entryPoint",
             "type":"address"
          }
       ],
       "name":"setEntryPoint",
       "outputs":[
          
       ],
       "stateMutability":"nonpayable",
       "type":"function"
    },
    {
       "inputs":[
          {
             "internalType":"address",
             "name":"_webAuthnVerifier",
             "type":"address"
          }
       ],
       "name":"setWebAuthnVerifier",
       "outputs":[
          
       ],
       "stateMutability":"nonpayable",
       "type":"function"
    },
    {
       "inputs":[
          {
             "components":[
                {
                   "components":[
                      {
                         "internalType":"bytes32",
                         "name":"x",
                         "type":"bytes32"
                      },
                      {
                         "internalType":"bytes32",
                         "name":"y",
                         "type":"bytes32"
                      }
                   ],
                   "internalType":"struct IKey.PubKey",
                   "name":"pubKey",
                   "type":"tuple"
                },
                {
                   "internalType":"address",
                   "name":"eoaAddress",
                   "type":"address"
                },
                {
                   "internalType":"enum IKey.KeyType",
                   "name":"keyType",
                   "type":"uint8"
                }
             ],
             "internalType":"struct IKey.Key",
             "name":"_recoveryKey",
             "type":"tuple"
          }
       ],
       "name":"startRecovery",
       "outputs":[
          
       ],
       "stateMutability":"nonpayable",
       "type":"function"
    },
    {
       "inputs":[
          {
             "internalType":"bytes32",
             "name":"mode",
             "type":"bytes32"
          }
       ],
       "name":"supportsExecutionMode",
       "outputs":[
          {
             "internalType":"bool",
             "name":"",
             "type":"bool"
          }
       ],
       "stateMutability":"view",
       "type":"function"
    },
    {
       "inputs":[
          {
             "internalType":"bytes4",
             "name":"_interfaceId",
             "type":"bytes4"
          }
       ],
       "name":"supportsInterface",
       "outputs":[
          {
             "internalType":"bool",
             "name":"",
             "type":"bool"
          }
       ],
       "stateMutability":"pure",
       "type":"function"
    },
    {
       "inputs":[
          {
             "internalType":"address",
             "name":"",
             "type":"address"
          },
          {
             "internalType":"address",
             "name":"",
             "type":"address"
          },
          {
             "internalType":"address",
             "name":"",
             "type":"address"
          },
          {
             "internalType":"uint256",
             "name":"",
             "type":"uint256"
          },
          {
             "internalType":"bytes",
             "name":"",
             "type":"bytes"
          },
          {
             "internalType":"bytes",
             "name":"",
             "type":"bytes"
          }
       ],
       "name":"tokensReceived",
       "outputs":[
          
       ],
       "stateMutability":"pure",
       "type":"function"
    },
    {
       "inputs":[
          {
             "internalType":"address",
             "name":"newImplementation",
             "type":"address"
          }
       ],
       "name":"upgradeProxyDelegation",
       "outputs":[
          
       ],
       "stateMutability":"nonpayable",
       "type":"function"
    },
    {
       "inputs":[
          {
             "internalType":"bytes32",
             "name":"",
             "type":"bytes32"
          }
       ],
       "name":"usedChallenges",
       "outputs":[
          {
             "internalType":"bool",
             "name":"",
             "type":"bool"
          }
       ],
       "stateMutability":"view",
       "type":"function"
    },
    {
       "inputs":[
          {
             "components":[
                {
                   "internalType":"address",
                   "name":"sender",
                   "type":"address"
                },
                {
                   "internalType":"uint256",
                   "name":"nonce",
                   "type":"uint256"
                },
                {
                   "internalType":"bytes",
                   "name":"initCode",
                   "type":"bytes"
                },
                {
                   "internalType":"bytes",
                   "name":"callData",
                   "type":"bytes"
                },
                {
                   "internalType":"bytes32",
                   "name":"accountGasLimits",
                   "type":"bytes32"
                },
                {
                   "internalType":"uint256",
                   "name":"preVerificationGas",
                   "type":"uint256"
                },
                {
                   "internalType":"bytes32",
                   "name":"gasFees",
                   "type":"bytes32"
                },
                {
                   "internalType":"bytes",
                   "name":"paymasterAndData",
                   "type":"bytes"
                },
                {
                   "internalType":"bytes",
                   "name":"signature",
                   "type":"bytes"
                }
             ],
             "internalType":"struct PackedUserOperation",
             "name":"userOp",
             "type":"tuple"
          },
          {
             "internalType":"bytes32",
             "name":"userOpHash",
             "type":"bytes32"
          },
          {
             "internalType":"uint256",
             "name":"missingAccountFunds",
             "type":"uint256"
          }
       ],
       "name":"validateUserOp",
       "outputs":[
          {
             "internalType":"uint256",
             "name":"validationData",
             "type":"uint256"
          }
       ],
       "stateMutability":"nonpayable",
       "type":"function"
    },
    {
       "inputs":[
          
       ],
       "name":"webAuthnVerifier",
       "outputs":[
          {
             "internalType":"address",
             "name":"",
             "type":"address"
          }
       ],
       "stateMutability":"view",
       "type":"function"
    },
    {
       "stateMutability":"payable",
       "type":"receive"
    }
 ]