name: CI

env:
  ETHERSCAN_KEY: ${{ secrets.ETHERSCAN_KEY }}
  SEPOLIA_RPC_URL: ${{ secrets.SEPOLIA_RPC_URL }}
  ETHERSCAN_KEY_BASE: ${{ secrets.ETHERSCAN_KEY_BASE }}
  SEPOLIA_BASE_RPC_URL: ${{ secrets.SEPOLIA_BASE_RPC_URL }}
  ADDRESS_OPENFORT_USER_ADDRESS_7702: ${{ secrets.ADDRESS_OPENFORT_USER_ADDRESS_7702 }}
  PRIVATE_KEY_OPENFORT_USER_7702: ${{ secrets.PRIVATE_KEY_OPENFORT_USER_7702 }}
  IMPLEMENTATION_CONTRACT: ${{ secrets.IMPLEMENTATION_CONTRACT }}
  ERC20_ADDRESS: ${{ secrets.ERC20_ADDRESS }}
  ENTRY_POINT_ADDRESS_V8: ${{ secrets.ENTRY_POINT_ADDRESS_V8 }}
  PIMLICO_API_KEY: ${{ secrets.PIMLICO_API_KEY }}
  PRIVATE_KEY_SENDER: ${{ secrets.PRIVATE_KEY_SENDER }}
  PRIVATE_KEY_SESSIONKEY: ${{ secrets.PRIVATE_KEY_SESSIONKEY }}
  GUARDIAN_EOA_PRIVATE_KEY: ${{ secrets.GUARDIAN_EOA_PRIVATE_KEY }}

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  check:
    name: Foundry project
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true

    steps:
      - name: Checkout repository with submodules
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          # You can pin to your local exact version instead (e.g. nightly-2025-07-10)
          version: nightly

      - name: Show Forge version
        run: forge --version

      - name: Run Forge fmt
        id: fmt
        run: forge fmt --check

      - name: Run Forge build
        id: build
        run: forge build --sizes --profile ci

      - name: Run Forge tests
        id: test
        run: forge test -vvv --profile ci --rpc-url "$SEPOLIA_RPC_URL"
